output "eks_cluster_id" {
  description = "Amazon EKS Cluster Id"
  value       = try(module.eks.cluster_id, null)
}

output "cluster_name" {
  description = "Amazon EKS Cluster Id"
  value       = try(module.eks.cluster_name, null)
}

output "eks_cluster_endpoint" {
  description = "Amazon EKS Cluster Endpoint"
  value       = try(module.eks.cluster_endpoint, null)
}

output "eks_cluster_certificate_authority_data" {
  description = "CA cert for Cluster"
  value       = try(module.eks.cluster_certificate_authority_data, null)
}

output "eks_cluster_managed_node_groups" {
  description = "Cluster Node Group"
  value = [
    for ng in module.eks.eks_managed_node_groups : ng
  ]
}

output "eks_ami_id" {
  description = "AMI Node"
  value       = var.automatic_ami_update_enabled ? coalesce(var.ami_id, data.aws_ami.eks_default_ami[0].image_id) : var.ami_id
}

output "cluster_security_group_id" {
  description = "Cluster Security Group"
  value       = try(module.eks.cluster_security_group_id)
}

output "eks_node_security_group_id" {
  description = "Node Security Group"
  value       = try(module.eks.node_security_group_id)
}

output "alb_load_balancer_hostnames" {
  description = "Endpoints from all Istio Ingress ALBs"
  value = var.create_alb ? {
    for k, v in kubernetes_ingress_v1.ingress :
    k => try(v.status[0].load_balancer[0].ingress[0].hostname, "")
  } : {}
}

output "aws_auth_configmap_yaml" {
  description = "AWS auth ConfigMap YAML generated by the EKS module"
  value       = try(module.eks.aws_auth_configmap_yaml, "")
}
